### ISSUE TITLE
Scatter Plot Grasshopper Empty Output Window

### ISSUE THREAD

**Issue by rynaldi95** [ksobon/Mandrill#62]
hi, i'm rynaldi. I'm working on a project with grasshopper and i'm kind of new to this software.

I want to make scatter plot with mandrill, however, the output window is always empty both by inputting data manually and retrieving data from CSV.
I tried with other chart (bar chart) and it works well. Do you have any recommendation or correction? I'm wondering if my input data is wrong, but I cannot find it.

I'm using Rhino 6 and Mandrill for Rhino 6. Attached you can find the grasshopper and simple CSV file that I make (just for testing purpose).

Thank you in advance

![image](https://user-images.githubusercontent.com/47637713/79500412-abf38100-802c-11ea-9e86-5a7bdb686728.png)

[ScatterTest.zip](https://github.com/BadMonkeysTeam/Mandrill/files/4489483/ScatterTest.zip)

**Comment by ksobon** [comment]
@rynaldi95 thanks for reporting. I think I was able to fix the bug. Here's a new version: 

![image](https://user-images.githubusercontent.com/529781/79526048-03dcb880-802a-11ea-8f25-721528220cec.png)

Cheers!

**Comment by ayezioro** [comment]
Hi,
Also I am  just testing this plugin. I took the example above, updated all components but the window is still empty.
As a matter of fact all examples I'm trying are faulty.
Will be nice to have a good set of working examples, including the data files, since there is no other explanation in order to understand the working flow. I see the potential of the plugin, but can't make it work.
Will appreciate your help.
Best regards,
-A.

**Comment by ksobon** [comment]
@ayezioro got a min to get on a call? I think it will be easier to try and fix the issue if I can see what the install looks like, and what's the data.

**Comment by ayezioro** [comment]
Hi @ksobon,
Sure. Thank you!!
How you suggest to do it?
-A.

**Comment by ksobon** [comment]
https://calendly.com/konradsobon/quick-meet

**Comment by rafael-a** [comment]
@ksobon, @ayezioro did you find a solution to this?

I downloaded the last version of the GH plugin, but can´t get any graph plotted on the window. PDF reports work well though.

**Comment by ayezioro** [comment]
@rafael-a,
I don't know if your issue is the same as mine. The solution for mine was to copy the eowp.exe file, located at the C:\Users\YOURUSER\AppData\Roaming\Grasshopper\Libraries\Mandrill folder into the C:\Program Files\Rhino 6\Plug-ins\Grasshopper.
@ksobon will try to solve this issue in a better manner, but in the meantime this is how it works for me.
-A.

**Comment by rafael-a** [comment]
That worked, @ayezioro.
Thank you for the quick reply, all seems good now.

**Comment by rynaldi95** [comment]
@ksobon,
sorry for the late reply.
thanks a lot for the fix. It works perfectly well!
I have another question, I'm just wondering if its actually possible to plot a histogram with Mandrill?
I know it's a bit off topic, but I just want to know if it's possible. If yes, I will open a new thread regarding this.
